
export const state = () => {
    return {
        documentType: [
            {value:'ACMIL', name:'TESS. APP.TO AG.CUSTODIA'},
            {value:'ACSOT', name: 'TESS. SOTT.LI AG.CUSTODIA'},
            {value:'ACUFF', name: 'TESS. UFF.LI AG.CUSTODIA'},
            {value:'AMMIL', name: 'TESS. MILITARE TRUPPA A.M'},
            {value:'AMSOT', name: 'TESS. SOTTUFFICIALI A.M.'},
            {value:'AMUFF', name: 'TESS. UFFICIALI A.M.'},
            {value:'CCMIL', name: 'TESS. APP.TO CARABINIERI'},
            {value:"CCSOT", name: 'TESS. SOTTUFFICIALI CC'},
            {value:'CCUFF', name: 'TESS. UFFICIALE'},
            {value:'CERID', name: "CERTIFICATO D'IDENTITA"},
            {value:'CFMIL', name: 'TESS. AG. E AG.SC. C.F.S.'},
            {value:'CFSOT', name: 'TESS. SOTTUFICIALI C.F.S.'},
            {value:'CFUFF', name: 'TESS. UFFICIALI C.F.S.'},
            {value:'CIDIP', name: 'CARTA ID. DIPLOMATICA'},
            {value:'DESIS', name: 'TESS. S.I.S.D.E.'},
            {value:'EIMIL', name: 'TESS. MILITARE E.I.'},
            {value:'EISOT', name: 'TESS. SOTTUFFICIALI E.I.'},
            {value:'EIUFF', name: 'TESS. UFFICIALI E.I.'},
            {value:'GFMIL', name: 'TESS. APP.TO FINANZIERE'},
            {value:'GFSOT', name: 'TESS. SOTT.LI G.D.F.'},
            {value:'GFTRI', name: 'TESS. POL. TRIB. G.D.F.'},
            {value:'GFUFF', name: 'TESS. UFFICIALI G.D.F.'},
            {value:'IDELE', name: "CARTA IDENTITA' ELETTRONICA"},
            {value:'IDENT', name: 'CARTA DI IDENTITA'},
            {value:'MAGIS', name: 'TESS. PERS. MAGISTRATI'},
            {value:'MMMIL', name: 'TESS. MILIT. M.M.'},
            {value:'MMSOT', name: 'TESS. SOTTUFICIALI M.M.'},
            {value:'MMUFF', name: 'TESS. UFFICIALI M.M.'},
            {value:'PARLA', name: 'TESS. PARLAMENTARI'},
            {value:'PASDI', name: 'PASSAPORTO DIPLOMATICO'},
            {value:'PASOR', name: 'PASSAPORTO ORDINARIO'},
            {value:'PASSE', name: 'PASSAPORTO DI SERVIZIO'},
            {value:'PATEN', name: 'PATENTE DI GUIDA'},
            {value:'PATNA', name: 'PATENTE NAUTICA'},
            {value:'PPAGE', name: 'TESS. AGENTI/ASS.TI P.P.'},
            {value:'PPISP', name: 'TESS. ISPETTORI P.P.'},
            {value:'PPSOV', name: 'TESS. SOVRINTENDENTI P.P.'},
            {value:'PPUFF', name: 'TESS. UFFICIALI P.P.'},
            {value:'PSAPP', name: 'TESS. AGENTI/ASS.TI P.S.'},
            {value:'PSFEM', name: 'TESS. POLIZIA FEMMINILE'},
            {value:'PSFUN', name: 'TESS. FUNZIONARI P.S.'},
            {value:'PSISP', name: 'TESS. ISPETTORI P.S.'},
            {value:'PSSOT', name: 'TESS. SOVRINTENDENTI P.S.'},
            {value:'PSUFF', name: 'TESS. UFFICIALI P.S.'},
            {value:'SDMIL', name: 'TESS. MILIT. TRUPPA SISMI'},
            {value:'SDSOT', name: 'TESS. SOTTUFFICIALI SISMI'},
            {value:'SDUFF', name: 'TESS. UFFICIALI SISMI'},
            {value:'TEAMC', name: 'TESS. ISCR. ALBO MED/CHI.'},
            {value:'TEAOD', name: 'TESS. ISCRIZ. ALBO ODONT.'},
            {value:'TECAM', name: 'TES. UNICO PER LA CAMERA'},
            {value:'TECOC', name: 'TESS. CORTE DEI CONTI'},
            {value:'TEDOG', name: 'TES.DOGANALE RIL.MIN.FIN.'},
            {value:'TEFSE', name: 'TESS. FERROV. SENATO'},
            {value:'TEMPI', name: 'TESS. MIN.PUBB.ISTRUZIONE'},
            {value:'TENAT', name: 'TESS. MILITARE NATO'},
            {value:'TENAV', name: 'TES. ENTE NAZ. ASSIS.VOLO'},
            {value:'TEPOL', name: 'TESS.MIN.POLIT.AGRIC.FOR.'},
            {value:'TESAE', name: 'TESS. MIN. AFFARI ESTERI'},
            {value:'TESAR', name: 'TESS.ISCR.ALBO ARCHITETTI'},
            {value:'TESAV', name: 'TESSERA ISCR. ALBO AVVOC.'},
            {value:'TESCA', name: "TESS. CORTE D'APPELLO"},
            {value:'TESCS', name: 'TESS. CONSIGLIO DI STATO'},
            {value:'TESDI', name: 'TESSERA RICONOSC. D.I.A.'},
            {value:'TESEA', name: 'TESS. MEMBRO EQUIP. AEREO'},
            {value:'TESIN', name: 'TESS.ISCR. ALBO INGEGNERI'},
            {value:'TESLP', name: 'TESS. MINISTERO LAVORI PU'},
            {value:'TESMB', name: 'TESS. MIN.BEN.E ATT.CULT.'},
            {value:'TESMD', name: 'TESS. MINISTERO DIFESA'},
            {value:'TESMF', name: 'TESS. MINISTERO FINANZE'},
            {value:'TESMG', name: 'TESS. MINISTERO GIUSTIZIA'},
            {value:'TESMI', name: 'TESS. MINISTERO INTERNO'},
            {value:'TESMN', name: 'TESS. MINIST. TRASP/NAVIG'},
            {value:'TESMS', name: 'TESS. MINISTERO SANITA'},
            {value:'TESMT', name: 'TESS. MINISTERO TESORO'},
            {value:'TESNO', name: "TESSERA DELL'ORDINE NOTAI"},
            {value:'TESOG', name: 'TESS. ORDINE GIORNALISTI'},
            {value:'TESPC', name: 'TESS. PRES.ZA CONS. MIN.'},
            {value:'TESPI', name: 'TESS. PUBBLICA ISTRUZIONE'},
            {value:'TESPT', name: 'TES. POSTE E TELECOMUNIC.'},
            {value:'TESUN', name: 'TESSERA U.N.U.C.I.'},
            {value:'TETEL', name: 'TESS. IDENTIF.TELECOM IT.'},
            {value:'TFERD', name: 'TES. FERROVIARIA DEPUTATI'},
            {value:'TFEXD', name: 'TES. FERROV. EX DEPUTATI'},
            {value:'VIMIL', name: 'TESS. APP.TO/VIG. URBANO'},
            {value:'VISOT', name: 'TESS. SOTT.LI VIG. URBANI'},
            {value:'VIUFF', name: 'TESS. UFF.LI VIG.URBANI'},
            {value:'VVMIL', name: 'TESS. APP.TO/VIG. VV.FF.'},
            {value:'VVSOT', name: 'TESS. SOTTUFF.LI VV.FF.'},
            {value:'VVUFF', name: 'TESS. UFFICIALI VV.FF.'}
        ]
    }
}
